name: Release to nuget

on:
  release:
    types: [published]

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore
    - name: check files
      run: ls -la
      
    - name: Build Main
      run: dotnet build PortaCapena.OdooJsonRpcClient/PortaCapena.OdooJsonRpcClient.csproj --configuration Release
      
    - name: Build Shared
      run: dotnet build PortaCapena.OdooJsonRpcClient.Shared/PortaCapena.OdooJsonRpcClient.Shared.csproj --configuration Release
      
    - name: Build Example
      run: dotnet build PortaCapena.OdooJsonRpcClient.Example/PortaCapena.OdooJsonRpcClient.Example.csproj --configuration Release
          
    - name: Build Tests
      run: dotnet build PortaCapena.OdooJsonRpcClient.Tests/PortaCapena.OdooJsonRpcClient.Tests.csproj --configuration Release
      
    - name: Test PR      
      run: dotnet test PortaCapena.OdooJsonRpcClient.Tests/PortaCapena.OdooJsonRpcClient.Tests.csproj --configuration Release --no-restore --no-build
    - name: Publish to NuGet
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: PortaCapena.OdooJsonRpcClient/PortaCapena.OdooJsonRpcClient.csproj
        VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        
